### ISSUE TITLE
Bug in line X69

### ISSUE THREAD

**Issue by tursics** [tursics/thought-karte-pankow#12]
Oberfeldstraße is interruped. There is no way for busses. It's only possible to walk to the other side.

![image](https://user-images.githubusercontent.com/5406352/124367454-a5642000-dc57-11eb-9d69-60a3fb34120e.png)

**Comment by TorbenGreve** [comment]
Gut, dass Du mich auf den Fehler in Biesdorf hingewiesen hast. Würde dann den X69er in Biesdorf so lassen, wie er heute ist: Also auf direktem Weg über den Blumberger Damm, statt via S Biesdorf - damit, dann leider ohne Verknüpfung mit der S5.

**Comment by tursics** [comment]
fixed
