### ISSUE TITLE
Bug tram in Campus Buch

### ISSUE THREAD

**Issue by tursics** [tursics/thought-karte-pankow#13]
It's hard or may be not possible to get a tram line in Campus Buch. What's the best way?

![image](https://user-images.githubusercontent.com/5406352/124367555-75694c80-dc58-11eb-91a5-1ebd9c24b934.png)

What's the prefered way south of Campus Buch? Through existing KGA and Siedlungsring and freeway?

![image](https://user-images.githubusercontent.com/5406352/124367587-d002a880-dc58-11eb-82ea-872308289439.png)

**Comment by TorbenGreve** [comment]
Dazu schicke ich Dir gleich einen Lösungsvorschlag per Signal!

**Comment by tursics** [comment]
fixed
