### ISSUE TITLE
Bug U2 and U8 station Pankow

### ISSUE THREAD

**Issue by tursics** [tursics/thought-karte-pankow#14]
It's not possible to connect U2 and U8 in one station in U Pankow. U2 is a Kleinprofil, U8 is a Großprofil. May be build a cross station. Take care of the Kehr- and Abstellanlage.

![image](https://user-images.githubusercontent.com/5406352/124367805-c8dc9a00-dc5a-11eb-91d2-c64ae5a296cd.png)

**Comment by TorbenGreve** [comment]
Hab Dir gerade ein Bild mit einem Alternativvorschlag per Signal geschickt.

**Comment by tursics** [comment]
fixed
