### ISSUE TITLE
Bug in clipping Pankow with new eXpress bus lines

### ISSUE THREAD

**Issue by tursics** [tursics/thought-karte-pankow#15]
The new bus line X3 beginns in Buch and most of the way to the destination is located outside Berlin. If I clip the boundaries of Pankow only a little part still be visible.

![image](https://user-images.githubusercontent.com/5406352/124981260-a5886500-e035-11eb-9af7-ee527b49aab6.png)

**Comment by TorbenGreve** [comment]
Hi Thomas, wie am Telefon gesagt: Aus meiner Sicht sollte man immer den kompletten Linienverlauf sehen können, aber immer nur von den Linien, die den ausgewählten Stadtteil bedienen.

**Comment by tursics** [comment]
Das ist eine sehr gute Idee. Ich habe das jetzt umgesetzt.

![image](https://user-images.githubusercontent.com/5406352/126085554-5a501308-f96c-4f1b-8d1d-c2aa8878d5a0.png)
